repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-shebang-scripts-are-executable
- repo: https://github.com/exdial/pre-commit-hooks
  rev: v0.0.6
  hooks:
  - id: packer-validate
  - id: packer-fmt
